config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      post :cancel_vote
    end
  end

  resources :questions,
            except: [:edit, :new],
            concerns: [:votable] do
    resources :answers,
              concerns: [:votable],
              shallow: true,
              except: [:index, :edit, :new] do
      member do
        post :best
      end

      resources :comments, only: [:create], defaults: { context: 'answer' }
    end

    resources :comments, only: [:create], defaults: { context: 'question' }
  end

  root 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable

  has_many :answers, dependent: :destroy
  has_many :best_answers, -> { where(best: true) },
    class_name: "Answer"

  belongs_to :user

  validates :title, :body, :user_id, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  skip_before_action :authenticate_user!, only: [:index, :show]

  before_action :set_question, only: [:show, :destroy, :update]

  after_action :publish_question, only: [:create]

  def index
    @questions = policy_scope(Question).includes(:user)
  end

  def show
    gon.question_user_id = @question.user_id
  end

  def create
    authorize Question
    @question = current_user.questions.create(question_params)
    render_json @question
  end

  def destroy
    @question.destroy
    redirect_to questions_path, notice: t('.message')
  end

  def update
    @question.update(question_params)
    render_json @question
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end

  def set_question
    @question = Question.find(params[:id])
    authorize @question
    gon.question_id = @question.id
  end

  def publish_question
    return if @question.errors.any?
    ActionCable.server.broadcast(
      "questions",
      {
        question: ApplicationController.render(
          locals: { question: @question },
          partial: 'questions/question'
        )
      }
    )
  end
end

app/views/questions/_answers.html.slim
.answers-content
  .answers.collection#answers_list
    - @question.answers.includes(:user).each do |answer|
      = render answer

app/views/questions/_form.html.slim
#question_form style="display: none;"
  = form_for @question || :question, remote: true do |f|
    .row
      .input-field.col.s12
        =f.text_field :title
        =f.label :title
    .row
      .input-field.col.s12
        =f.label :body
        =f.text_area :body, class: 'materialize-textarea'
    .row
      .col
        =f.submit "Save", class: 'waves-effect waves-light btn'
      .col
        .btn.cancel-btn.grey.waves-effect.waves-light.lighten-4.black-text Cancel

app/views/questions/_question.html.slim
.collection-item id=dom_id(question)
  span.title
    = link_to question.title, question_path(question)
  p =question.user&.email

app/views/questions/_question_block.html.slim
.question-info#question_info
  .section
    h5.question-title =@question.title
    p.question-body =@question.body 
    = render 'shared/votes', votable: @question
  .question-controls
    .row
      - if allowed_to?(:update?, @question)
        .col
          = link_to 'Edit', '', class: 'edit-question-link', id: "add_question_btn"
      - if allowed_to?(:destroy?, @question)
        .col
          = link_to 'Delete', @question, method: :delete

= render 'form'
  / = render 'comments/list', commentable: @question, comment: @question.comments.build

app/views/questions/index.html.slim
h3 Questions
.questions-list.collection
  - if @questions.any?
    = render @questions
  - else
    div
      .col.s6.offset-s3.center No questions found(

- if policy(Question).create?
  = render 'shared/add_btn', id: "add_question_btn"
  = render 'form'

= content_for :scripts
  = javascript_include_tag 'questions'

app/views/questions/show.html.slim
= render 'question_block'

= render 'answers'

- if policy(Answer).create?
  = render 'shared/add_btn', id: "add_answer_btn"
  = render 'answers/form', id: 'new_answer_form', answer: @question.answers.new

= content_for :scripts
  = javascript_include_tag 'answers'

app/views/questions/update.js.erb
<% if @question.valid? %>
  $('div.question').html('<%= j render "question_block" %>');
<% else %>
  $('div#edit-question-form-container #validation-errors').html('<%= j render "validation_errors" %>');
<% end %>