config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  concern :votable do
    member do
      post :vote_up
      post :vote_down
      post :cancel_vote
    end
  end

  resources :questions,
            except: [:edit, :new],
            concerns: [:votable] do
    resources :answers,
              concerns: [:votable],
              shallow: true,
              except: [:index, :edit, :new] do
      member do
        post :best
      end

      resources :comments, only: [:create], defaults: { context: 'answer' }
    end

    resources :comments, only: [:create], defaults: { context: 'question' }
  end

  root 'questions#index'

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable

  belongs_to :question
  belongs_to :user

  validates :body, :question_id, :user_id, presence: true

  default_scope -> { order(best: :desc) }

  scope :best, -> { where(best: true) }

  def make_best
    ActiveRecord::Base.transaction do
      question.answers.update_all(best: false)
      update!(best: true)
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :set_question, only: [:create]
  before_action :set_answer, only: [:destroy, :update, :best]

  def create
    authorize Answer
    @answer = @question.answers.create(
      answer_params.merge(user: current_user)
    )
    render_json @answer
  end

  def destroy
    @answer.destroy
    render_json_message
  end

  def update
    @answer.update(answer_params)
    render_json @answer
  end

  def best
    @answer.make_best
    render_json @answer
  end

  private

  def answer_params
    params.require(:answer).permit(:body)
  end

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
    authorize @answer
  end
end

app/views/answers/_answer.html.slim
.answer.collection-item.section id=dom_id(answer)
  .answer-info
    - if answer.best?
      span.badge.green.white-text.answer-best-badge best
    p.answer-body =answer.body
    p =answer.user&.email

    = render 'shared/votes', votable: answer

    .answer-controls
      .row
        - if policy(answer).update?
          .col
            = link_to 'Edit', '#', class: 'edit-answer-link'
        - if policy(answer).destroy?
          .col
            = link_to 'Delete', answer, method: :delete, remote: true, class: 'delete-answer-link'
        - if policy(answer).best?
          .col
            = link_to 'Best answer', best_answer_path(answer),
                remote: true,
                method: :post,
                class: 'best-answer-link'
  - if policy(answer).update?
    = render 'answers/form', id: "answer_form_#{answer.id}", answer: answer

  / = render partial: 'comments/list', locals: { commentable: answer, comment: answer.comments.build }

app/views/answers/_form.html.slim
.answer-edit-form style="display: none;" id="#{ local_assigns.fetch(:id, nil) }"
  = form_for shallow_resource(@question, answer), remote: true do |f|
    .row
      .input-field.col.s12
        =f.label :body
        =f.text_area :body, class: 'materialize-textarea'
    .row
      .col
        =f.submit "Save", class: 'waves-effect waves-light btn'
      .col
        .btn.cancel-btn.grey.waves-effect.waves-light.lighten-4.black-text Cancel

app/views/answers/best.js.erb
$('p#best-answer').remove();
$('div#<%= dom_id @answer %> p.answer-body').after('<p id="best-answer">Best answer</p>');

app/views/answers/create.js.erb
<% if @answer.valid? %>
  $('div.answers div.answers-list').append('<%= j render partial: @answer, locals: { answer: @answer } %>');
  $('form#new_answer p textarea').val('');
  $('form#new_answer div input[type="file"]').val('');
<% else %>
  $('<%= j render 'answers/validation_errors' %>').insertBefore($('#new-answer-form form'));
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $('p.notice').text('Your answer deleted.');
  $('div#<%= dom_id @answer %>').remove();
<% end %>

app/views/answers/update.js.erb
<% if @answer.valid? %>
  $("div#<%= dom_id @answer %>").html(
    '<%= j render partial: @answer, locals: { answer: @answer } %>'
  );
<% else %>
  $('<%= j render 'answers/validation_errors' %>').insertBefore($('.edit-answer-form form'));
<% end %>